/* craco.config.js */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const CircularDependencyPlugin = require('circular-dependency-plugin')

module.exports = {
  webpack: {
    plugins: [
      new CircularDependencyPlugin({
        exclude: /a\.js|node_modules/,
        onStart({ compilation }) {
          console.log('start detecting webpack modules cycles')
        },
        // `onDetected` is called for each module that is cyclical
        onDetected({ compilation, module: webpackModuleRecord, paths }) {
          // `paths` will be an Array of the relative module paths that make up the cycle
          // `module` will be the module record generated by webpack that caused the cycle
          compilation.errors.push(new Error(paths.join(' -> ')))
        },
        // `onEnd` is called before the cycle detection ends
        onEnd({ compilation }) {
          console.log('end detecting webpack modules cycles')
        },
      }),
    ],
  },
  entry: './src/index',
}
