const theme = {
  fonts: {
    defaultSize: '14px',
    fontFamily: `'Roboto', 'Helvetica Neue', 'Arial', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', '-apple-system', 'BlinkMacSystemFont', sans-serif`,
    fontFamilyCode: `source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace`,
  },
  buttonPrimary: {
    backgroundColor: '#1565C0',
    backgroundColorHover: '#0d4584',
    borderColor: '#1565C0',
    borderColorHover: '#0d4584',
    color: '#fff',
    colorHover: '#fff',
  },
  buttonPrimaryLine: {
    backgroundColor: '#fff',
    backgroundColorHover: '#fff',
    borderColor: '#1565C0',
    borderColorHover: '#0d4584',
    color: '#1565C0',
    colorHover: '#0d4584',
  },
  buttonSecondary: {
    backgroundColor: '#E3F2FD',
    backgroundColorHover: '#d1e1ec',
    borderColor: '#E3F2FD',
    borderColorHover: '#d1e1ec',
    color: '#1565C0',
    colorHover: '#1565C0',
  },
  buttonSecondaryLine: {
    backgroundColor: '#fff',
    backgroundColorHover: '#fff',
    borderColor: '#D6EBFD',
    borderColorHover: '#bfd1e2',
    color: '#37474F',
    colorHover: '#37474F',
  },
  colors: {
    activeListItemBackground: '#fafafa',
    darkGray: '#acacac',
    error: '#fa0000',
    gray: '#b7b7b7',
    mainBodyBackground: '#fff',
    primary: '#1565C0',
    secondary: '#E3F2FD',
    tertiary: '#D6EBFD',
    textColor: '#757575',
    textColorLight: '#999',
    textColorDark: '#37474F',
    warning: '#37474F',
  },
  cards: {
    backgroundColor: '#fff',
    border: '1px solid #EEE',
    borderRadius: '8px ',
    boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.05)',
    paddingHorizontal: '25px',
    paddingVertical: '25px',
    textColor: '#000',
    textColorSecondary: '#333',
    titleColor: '#000',
  },
  header: {
    backgroundColor: '#fff',
    boxShadow: 'none',
    height: '66px',
    color: '#37474F',
  },
  themeBreakPoints: {
    lg: '992px',
    md: '768px',
    sm: '480px',
    xl: '1024px',
    xs: '320px',
    xxl: '1280px',
    xxxl: '1366px',
  },
  borders: {
    borderColor: '#ECEFF1',
    commonBorderRadius: '6px',
  },
  paddings: {
    mainPadding: '15px',
  },
  textfield: {
    backgroundColor: 'transparent',
    borderColor: '#999',
    borderRadius: '0',
    borderStyle: 'solid',
    borderWidth: '1px',
    color: '#333',
    fontSize: '13px',
    fontWeight: '400',
    outline: 'none',
    paddingHorizontal: '4px',
    paddingVertical: '6px',
    placeholderColor: '#999',
  },
  createSteps: {
    maxWidth: '586px',
  },
  viewMarket: {
    maxWidth: '586px',
  },
  list: {
    maxWidth: '586px',
  },
  dropdown: {
    backgroundColor: '#fff',
    border: 'none',
    borderRadius: '5px',
    boxShadow: '0 0 12px 0 rgba(0, 0, 0, 0.12)',
    lightTextColor: '#666',
    textColor: '#000',
  },
  modalStyle: {
    content: {
      backgroundColor: '#fff',
      borderColor: 'transparent',
      borderRadius: '5px',
      bottom: 'auto',
      boxShadow: '0 0 18px 0 rgba(0, 0, 0, 0.08)',
      display: 'flex',
      flexDirection: 'column',
      flexGrow: '0',
      height: 'fit-content',
      left: 'auto',
      margin: 'auto 0',
      overflow: 'hidden',
      padding: '15px 20px',
      position: 'relative',
      right: 'auto',
      top: 'auto',
      width: '350px',
    },
    overlay: {
      alignItems: 'unset',
      backgroundColor: 'rgba(255, 255, 255, 0.75)',
      display: 'flex',
      justifyContent: 'center',
      overflow: 'auto',
      padding: '10px',
      zIndex: '12345',
    },
  },
}

export default theme
